homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('confirmation', views.confirmation, name='confirmation'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models
from datetime import datetime

class Message(models.Model):
    name= models.CharField('name', max_length = 100)
    message = models.TextField('message', max_length = 100)

    def __str__(self):
        return self.name

homepage/forms.py
from django import forms
from .models import Message

class MessageForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : "Write your name here",
        'type' : 'text',
        'maxlength' : '100',
        'required' : True,
        'label' : '',
    }))
    message = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : "I'm feeling...",
        'type' : 'text',
        'maxlength' : '100',
        'required' : True,
        'label' : '',
    }))

homepage/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Message
from . import forms
from .forms import MessageForm

# Create your views here.
def index(request):
    message = Message.objects.all()
    if request.method == "POST":
        form = MessageForm(request.POST)
        if (form.is_valid()):
            user_name = form.cleaned_data['name']
            user_message = form.cleaned_data['message']
            response = {'name':user_name, 'message':user_message}
            return render(request, 'confirmation.html', response)
    else:
        form = MessageForm()
    return render(request, 'index.html', {'message' : message})

def confirmation(request):
    if request.method == "POST":
        form = MessageForm(request.POST)
        if (form.is_valid()):
            name = form.cleaned_data['name']
            message = form.cleaned_data['message']
            new_message = Message.objects.create(name=name, message=message)
            new_message.save()
            return redirect('homepage:index')
    else:
        form = MessageForm()
    return render(request, 'confirmation.html')

homepage/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body style="background-color: #d4ebd0">
      {% block content %}

      {% endblock %}
      <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
<script>
    function change() {
        var x = document.getElementsByClassName("target");
        var i;
        for(i = 0; i < x.length; i++) {
            x[i].style.color = "rgba(237,102,99, 0.8)";
        }
    }
</script>
</html>

homepage/templates/confirmation.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<br><br><br><br>
<h1>Are you sure?</h1>
<form action="{% url 'homepage:confirmation' %}" method="POST">
    {% csrf_token %}
    <div style="margin-left: 10px; margin-right: 10px;">
        <div class="form-row">
            <div class="col-sm-1"></div>
            <div class="form-group col-sm-10">
                <h2>Your name:</h2>
                <input type="text" class="form-control" id="name" name="name" maxlength="100" readonly value="{{ name }}">
                <br>
                <h2>Your message:</h2>
                <input type="text" class="form-control" id="message" name="message" maxlength="100" readonly value="{{ message }}">
            </div>
        </div>
    </div>
    <div class="container">
    <div class="row">
      <div class="col">
        <div class="form-row">
            <input id="submitBtn" name="yes" type="submit" class="btn btn-primary" value="Yes">
        </div>
      </div>
      <div class="col">
        <div class="form-row">
            <a id="submitBtn" name="no" class="btn btn-primary" href="{% url 'homepage:index' %}" id="cancel">
              <input type="button" class="btn" value="No" style="text-decoration: none;"></a>   
        </div>
      </div>
    </div>
</div>
</form> 


{% endblock %}

homepage/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<br><br><br>
<h1>Hello. How are you today?</h1>
<div class="container">
    <div class="row">
      <div class="col-sm-4">
      </div>
      <div class="col-sm-4" style="text-align: center;">
        <img class="envelope" src="{% static 'images/message.png' %}" alt="message">
      </div>
      <div class="col-sm-4">
    </div>
    </div>
</div>
<br>
<form method="POST">
    {% csrf_token %}
    <div style="margin-left: 10px; margin-right: 10px;">
    <div class="form-row">
        <div class="col-sm-1"></div>
        <div class="form-group col-sm-10">
            <h2>What is your name?</h2>
            <input type="text" class="form-control" id="name" name="name" maxlength="100" placeholder="Write your name here" required>
            <br>
            <h2>Mind to share?</h2>
            <input type="text" class="form-control" id="message" name="message" maxlength="100" placeholder="I'm feeling..." required>
        </div>
    </div>
    <div class="form-row">
            <input id="submitBtn" name="postmessage" type="submit" class="btn btn-primary" value="Post My Message">
    </div>
</form>
<br><br>
<div class="moodBoard">
<h1>Mood Board</h1>
<button onclick="change()" id="changeColor" class="btn btn-primary">Change Font Color</button>
<br>
{% for message in message %}
    <div class="box">
    <p class="target" style="text-align: left;"> "{{ message.message }}" </p>
    <p class="target" style="text-align: right; font-size: 20px;">From: {{ message.name }}</p>
    </div>
    <br>
{% endfor %}
</div>
<br><br>
{% endblock %}